
carpeta_datos: "${CARPETA_DATOS}"
carpeta_figuras: "${CARPETA_FIGURAS}"
corregir: !!bool True

desc_variables:
  pr: 'Acumulado semanal de lluvia'
  tas: 'Temperatura media de la semana'

mapeo_variables:
  pr: 'precip'
  tas: 'tmean'
  tasmin: 'tmin'
  tasmax: 'tmax'
  zg: 'z200'

fechas_gmao:
  - [ mes, dia ]
  - [   1,   1 ]
  - [   1,   6 ]
  - [   1,  11 ]
  - [   1,  16 ]
  - [   1,  21 ]
  - [   1,  26 ]
  - [   1,  31 ]
  - [   2,   5 ]
  - [   2,  10 ]
  - [   2,  15 ]
  - [   2,  20 ]
  - [   2,  25 ]
  - [   3,   2 ]
  - [   3,   7 ]
  - [   3,  12 ]
  - [   3,  17 ]
  - [   3,  22 ]
  - [   3,  27 ]
  - [   4,   1 ]
  - [   4,   6 ]
  - [   4,  11 ]
  - [   4,  16 ]
  - [   4,  21 ]
  - [   4,  26 ]
  - [   5,   1 ]
  - [   5,   6 ]
  - [   5,  11 ]
  - [   5,  16 ]
  - [   5,  21 ]
  - [   5,  26 ]
  - [   5,  31 ]
  - [   6,   5 ]
  - [   6,  10 ]
  - [   6,  15 ]
  - [   6,  20 ]
  - [   6,  25 ]
  - [   6,  30 ]
  - [   7,   5 ]
  - [   7,  10 ]
  - [   7,  15 ]
  - [   7,  20 ]
  - [   7,  25 ]
  - [   7,  30 ]
  - [   8,   4 ]
  - [   8,   9 ]
  - [   8,  14 ]
  - [   8,  19 ]
  - [   8,  24 ]
  - [   8,  29 ]
  - [   9,   3 ]
  - [   9,   8 ]
  - [   9,  13 ]
  - [   9,  18 ]
  - [   9,  23 ]
  - [   9,  28 ]
  - [  10,   3 ]
  - [  10,   8 ]
  - [  10,  13 ]
  - [  10,  18 ]
  - [  10,  23 ]
  - [  10,  28 ]
  - [  11,   2 ]
  - [  11,   7 ]
  - [  11,  12 ]
  - [  11,  17 ]
  - [  11,  22 ]
  - [  11,  27 ]
  - [  12,   2 ]
  - [  12,   7 ]
  - [  12,  12 ]
  - [  12,  17 ]
  - [  12,  22 ]
  - [  12,  27 ]